if060-webui-RoR/Aid-Interview

.gitignore
app/assets/javascripts/questions.coffee
app/assets/stylesheets/questions.scss
app/controllers/questions_controller.rb
app/helpers/questions_helper.rb
app/models/question.rb
app/views/questions/index.html.erb
config/routes.rb
db/migrate/20151127194955_create_questions.rb
db/schema.rb
test/controllers/questions_controller_test.rb
test/fixtures/questions.yml
test/models/question_test.rb

As an admin user I want to be able to see a list of questions
+ pagination
+normal tab size

Question index

---

app/assets/stylesheets/custom.css.scss
app/controllers/questions_controller.rb
app/models/question.rb
app/models/topic.rb
app/views/questions/_all_questions.html.erb
app/views/questions/_form.html.erb
app/views/questions/_question.html.erb
app/views/questions/edit.html.erb
app/views/questions/index.html.erb
app/views/questions/new.html.erb
app/views/questions/show.html.erb
db/migrate/20151126173116_create_topics.rb
db/migrate/20151127194955_create_questions.rb
db/schema.rb
db/seeds.rb
test/fixtures/questions.yml
test/fixtures/topics.yml
test/fixtures/users.yml
test/integration/questions_create_test.rb
test/integration/questions_edit_test.rb
test/integration/questions_index_test.rb
test/integration/questions_show_test.rb
test/models/question_test.rb
test/models/topic_test.rb

recreate questions

---

README.md
README.rdoc
app/assets/stylesheets/custom.css.scss
app/views/admin/questions/_all_questions.html.slim
app/views/admin/questions/_form.html.slim
app/views/admin/questions/edit.html.slim
app/views/admin/questions/new.html.slim
db/migrate/20151207165057_change_string_to_text_in_questions.rb
db/schema.rb

Changed:
1. type for content and answer fields from string to text;
2. text_field to text_area + placeholder;
3. Fixed Readme.md

Finish use text type for content and answer fields of question model

---

db/seeds.rb

Filled in database with questions
https://trello.com/c/VKYCLLg5/36-add-seeds-with-real-data-for-questions-and-topics

Filled in database with questions

---

app/assets/stylesheets/custom.css.scss
app/helpers/devise_helper.rb
app/views/layouts/_messages.html.slim

Finish messages styles

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/custom.css.scss
app/controllers/admin/topics_controller.rb
app/views/admin/questions/_all_questions.html.slim
app/views/admin/questions/_question.html.slim
app/views/admin/questions/edit.html.slim
app/views/admin/questions/index.html.slim
app/views/admin/questions/new.html.slim
app/views/admin/questions/show.html.slim
app/views/admin/topics/_form.html.slim
app/views/admin/topics/index.html.slim
app/views/admin/topics/show.html.slim
app/views/admin/users/index.html.slim
config/environments/production.rb

Use bigger font size
https://trello.com/c/M6qnNkxG/28-use-bigger-fonts-size
Fix image uploading
Fix style issues
Fix question show page

Fix minor style issues

---

Gemfile
Gemfile.lock
app/assets/stylesheets/custom.css.scss
app/controllers/admin/questions_controller.rb
app/controllers/admin/templates_controller.rb
app/controllers/admin/topics_controller.rb
app/controllers/admin/users_controller.rb
app/controllers/application_controller.rb
app/views/layouts/_header.html.slim

code review:
https://trello.com/c/iRe1GXNT/34-add-breadcrumbs

breadcrumbs

---

app/assets/stylesheets/custom.css.scss
app/controllers/admin/questions_controller.rb
app/controllers/templates_controller.rb
app/views/admin/questions/_form.html.slim
app/views/admin/questions/index.html.slim
app/views/admin/topics/edit.html.slim
app/views/admin/topics/index.html.slim
app/views/admin/topics/show.html.slim
app/views/devise/passwords/new.html.slim
app/views/devise/registrations/new.html.slim
app/views/devise/sessions/new.html.slim
app/views/templates/_form.html.slim
app/views/templates/_template.html.slim
app/views/templates/edit.html.slim
app/views/templates/index.html.slim
app/views/templates/new.html.slim
app/views/templates/show.html.slim
app/views/users/show.html.slim

code review:
https://trello.com/c/OpfZOsP1/27-ensure-that-guest-user-not-logged-in-has-no-access-to-templates-functionality This task have been comleted earlie, so i just rewoked it to enshure that admin has no access to templates.
1. Admin has no access to templates
2. Styled templates pages
3. Some fixes

Admin have no access to templates

---

app/assets/javascripts/application.js
app/controllers/users/registrations_controller.rb
app/views/devise/registrations/edit.html.slim
app/views/layouts/_header.html.slim

code review:
https://trello.com/c/tZfDZkop/40-as-registered-user-i-want-to-be-able-edit-my-personal-data-and-reset-password

add the ability to edit user's data

---

app/assets/stylesheets/custom.css.scss
app/helpers/application_helper.rb
app/views/admin/dashboard/_admin_dashboard.html.slim
app/views/admin/dashboard/_panel.html.slim
app/views/users/show.html.slim
test/controllers/users_controller_test.rb

Add admin dashboard

---

Gemfile
Gemfile.lock
app/assets/stylesheets/custom.css.scss
app/controllers/admin/users_controller.rb
app/helpers/admin/users_helper.rb
app/views/admin/users/_search_form_for.html.slim
app/views/admin/users/index.html.slim

code review:
https://trello.com/c/Pzln1WRG/41-as-an-admin-when-on-users-index-i-want-to-be-able-to-search-for-user

Search and sort users with ransack

---

test/controllers/admin/templates_controller_test.rb
test/controllers/templates_controller_test.rb
test/factories/templates.rb
test/fixtures/templates.yml
test/models/template_test.rb

tests for templates

---

app/assets/stylesheets/custom.css.scss

Auth page: need to fix position of checkbox "Remember me"

---

app/assets/stylesheets/custom.css.scss

Reverts if060-webui-RoR/Aid-Interview#75

Revert "Auth page: need to fix position of checkbox "Remember me""

---

app/assets/stylesheets/custom.css.scss
app/controllers/admin/questions_controller.rb
app/controllers/admin/users_controller.rb
app/models/question.rb
app/models/topic.rb
app/views/admin/dashboard/_admin_dashboard.html.slim
app/views/admin/questions/_form.html.slim
app/views/admin/topics/_form.html.slim
app/views/admin/users/_user.html.slim
app/views/admin/users/index.html.slim
app/views/devise/registrations/edit.html.slim
app/views/interviews/_form.html.slim
app/views/layouts/_header.html.slim
app/views/templates/_form.html.slim
app/views/users/show.html.slim
db/seeds.rb
test/controllers/admin/questions_controller_test.rb
test/controllers/users_controller_test.rb
test/factories/users.rb
test/models/question_test.rb
test/models/topic_test.rb

code review:
There is no such task, but i think it will be usefull.
1. Admin able to delete not approved users.
2. Added length validation for questions and topic models.
3. Fixed questions and topic tests.
4. Added welcome message to admin dashboard.
5. Added close buttons to Activerecord arrors.
6. Some small style and bug fixes.
7. Added users seeds. (Didn't add pagination for user#index, coz saw that my teammate has allready done that in his PR)

Admin able to delete not approved users

---

app/assets/javascripts/fixed-scroll.coffee
app/assets/stylesheets/custom.css.scss
app/controllers/interviews_controller.rb
app/controllers/templates_controller.rb
app/helpers/interview_helper.rb
app/models/interview.rb
app/views/admin/questions/_question.html.slim
app/views/admin/topics/_form.html.slim
app/views/admin/topics/show.html.slim
app/views/interviews/_interview.html.slim
app/views/interviews/index.html.slim
app/views/interviews/new.html.slim
app/views/interviews/show.html.slim
app/views/layouts/_footer.html.slim
app/views/templates/index.html.slim

https://trello.com/c/KbjfNJhp/52-as-an-interviewer-i-should-be-able-to-see-summary-of-a-completed-interview
code review:
code review:

As an Interviewer I should be able to see summary of a completed interview

---

app/assets/stylesheets/custom.css.scss
app/controllers/admin/users_controller.rb
app/controllers/templates_controller.rb
app/views/admin/questions/_form.html.slim
app/views/admin/questions/_question.html.slim
app/views/admin/topics/index.html.slim
app/views/admin/users/index.html.slim
app/views/templates/_form.html.slim
app/views/templates/_template.html.slim
app/views/templates/edit.html.slim
app/views/templates/new.html.slim
app/views/templates/show.html.slim
app/views/users/show.html.slim
db/seeds.rb
test/controllers/templates_controller_test.rb
test/controllers/users_controller_test.rb
test/models/template_test.rb

add tooltips and update show_templates

---

app/views/admin/questions/_form.html.slim
app/views/admin/topics/_form.html.slim
app/views/interviews/_form.html.slim
app/views/shared/_error_messages.html.slim
app/views/templates/_form.html.slim

code review:
1. Added partial for error messages

Partial for error messages

---

app/assets/stylesheets/custom.css.scss
app/controllers/interviews_controller.rb
app/controllers/templates_controller.rb
app/models/template.rb
app/models/user.rb
app/views/interviews/_form.html.slim
db/migrate/20160101191032_add_user_id_to_templates.rb
db/schema.rb

to use only own templates

---

app/models/topic.rb

Fix default image on heroku displaying 
Make more correct image_url

Tiny fix for default image on heroku ( one line of code )

---

test/models/user_test.rb

test for edit user data

---

app/controllers/interview_questions_controller.rb
app/views/interview_questions/edit.html.slim

Adds some functions in interview
